import type { User, Ride, Notification } from "./types"

// Base de datos simulada
interface Database {
  users: User[]
  rides: Ride[]
  notifications: Notification[]
}

// Coordenadas ficticias para las ubicaciones
const locationCoords = {
  Universidad: { lat: -34.603722, lng: -58.381592 }, // Coordenadas ficticias para la universidad
  Palermo: { lat: -34.588446, lng: -58.412071 },
  Belgrano: { lat: -34.563589, lng: -58.452728 },
  Caballito: { lat: -34.619519, lng: -58.443642 },
  Recoleta: { lat: -34.58769, lng: -58.393288 },
  Núñez: { lat: -34.545021, lng: -58.461246 },
  Almagro: { lat: -34.610485, lng: -58.420257 },
  "Villa Crespo": { lat: -34.599819, lng: -58.436348 },
  "Barrio Norte": { lat: -34.595093, lng: -58.402256 },
  Colegiales: { lat: -34.577473, lng: -58.447766 },
  Flores: { lat: -34.628775, lng: -58.463593 },
  "San Telmo": { lat: -34.621076, lng: -58.373678 },
  Microcentro: { lat: -34.608418, lng: -58.373678 },
  "Puerto Madero": { lat: -34.610418, lng: -58.363678 },
  Retiro: { lat: -34.590418, lng: -58.373678 },
}

// Datos de ejemplo con usuarios que tienen múltiples roles
export const database: Database = {
  users: [
    // Usuario Administrador Principal
    {
      id: "admin-1",
      firstName: "Admin",
      lastName: "Universidad",
      legajo: "admin",
      dni: "99999999",
      email: "admin@universidad.edu",
      phone: "11-9999-9999",
      institutionalRole: ["admin"],
      uniRideRole: ["passenger"],
      password: "admin123",
      createdAt: "2023-01-01",
    },
    // Administrador que también es profesor y conductor
    {
      id: "admin-2",
      firstName: "Patricia",
      lastName: "Administradora",
      legajo: "admin2",
      dni: "98888888",
      email: "patricia.admin@universidad.edu",
      phone: "11-8888-8888",
      institutionalRole: ["admin", "professor"],
      uniRideRole: ["driver", "passenger"],
      password: "admin456",
      createdAt: "2023-01-02",
      createdBy: "admin-1",
    },
    // Profesor que es conductor y pasajero
    {
      id: "user-1",
      firstName: "Juan",
      lastName: "Pérez",
      legajo: "12345",
      dni: "30123456",
      email: "juan.perez@universidad.edu",
      phone: "11-1234-5678",
      institutionalRole: ["professor"],
      uniRideRole: ["driver", "passenger"],
      password: "profesor123",
      paymentMethods: [
        {
          id: "pm-1",
          cardNumber: "4111 **** **** 1111",
          cardHolder: "JUAN PEREZ",
          expiryDate: "12/25",
          type: "visa",
          isDefault: true,
        },
        {
          id: "pm-2",
          cardNumber: "5555 **** **** 5555",
          cardHolder: "JUAN PEREZ",
          expiryDate: "10/24",
          type: "mastercard",
        },
      ],
      rating: 4.8,
      reviews: [
        {
          id: "rev-1",
          reviewerId: "user-2",
          reviewerName: "María González",
          rating: 5,
          comment: "Excelente conductor, muy puntual y amable.",
          date: "2023-10-15",
        },
        {
          id: "rev-2",
          reviewerId: "user-3",
          reviewerName: "Carlos Rodríguez",
          rating: 4,
          comment: "Buen conductor, aunque a veces va un poco rápido.",
          date: "2023-11-20",
        },
      ],
      notifications: [
        {
          id: "notif-1",
          userId: "user-1",
          title: "Viaje iniciado",
          message: "Tu viaje a Universidad ha comenzado. ¡Buen viaje!",
          type: "info",
          read: true,
          date: new Date().toISOString(),
          relatedRideId: "ride-1",
        },
        {
          id: "notif-2",
          userId: "user-1",
          title: "Nuevo pasajero",
          message: "María González se ha unido a tu viaje a Universidad.",
          type: "success",
          read: false,
          date: new Date(Date.now() - 3600000).toISOString(),
          relatedRideId: "ride-1",
        },
      ],
      createdAt: "2023-01-15",
      createdBy: "admin-1",
    },
    // Estudiante que es conductor y pasajero
    {
      id: "user-2",
      firstName: "María",
      lastName: "González",
      legajo: "54321",
      dni: "31987654",
      email: "maria.gonzalez@universidad.edu",
      phone: "11-8765-4321",
      institutionalRole: ["student"],
      uniRideRole: ["driver", "passenger"],
      password: "estudiante456",
      paymentMethods: [
        {
          id: "pm-3",
          cardNumber: "3782 **** **** 3782",
          cardHolder: "MARIA GONZALEZ",
          expiryDate: "08/26",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.5,
      reviews: [
        {
          id: "rev-3",
          reviewerId: "user-1",
          reviewerName: "Juan Pérez",
          rating: 5,
          comment: "Muy buena conductora, siempre llega a tiempo.",
          date: "2023-09-05",
        },
        {
          id: "rev-4",
          reviewerId: "user-3",
          reviewerName: "Carlos Rodríguez",
          rating: 4,
          comment: "Conduce bien y es muy amable.",
          date: "2023-12-10",
        },
      ],
      notifications: [
        {
          id: "notif-3",
          userId: "user-2",
          title: "Viaje confirmado",
          message: "Te has unido al viaje de Juan Pérez a Universidad.",
          type: "success",
          read: true,
          date: new Date(Date.now() - 86400000).toISOString(),
          relatedRideId: "ride-1",
        },
        {
          id: "notif-4",
          userId: "user-2",
          title: "Viaje cercano",
          message: "Hay un nuevo viaje disponible desde Recoleta que podría interesarte.",
          type: "info",
          read: false,
          date: new Date().toISOString(),
          relatedRideId: "ride-10",
        },
      ],
      createdAt: "2023-02-20",
      createdBy: "admin-1",
    },
    // Profesor que es conductor y pasajero
    {
      id: "user-3",
      firstName: "Carlos",
      lastName: "Rodríguez",
      legajo: "67890",
      dni: "32456789",
      email: "carlos.rodriguez@universidad.edu",
      phone: "11-2345-6789",
      institutionalRole: ["professor"],
      uniRideRole: ["driver", "passenger"],
      password: "carlos789",
      paymentMethods: [
        {
          id: "pm-4",
          cardNumber: "4222 **** **** 4222",
          cardHolder: "CARLOS RODRIGUEZ",
          expiryDate: "03/27",
          type: "visa",
          isDefault: true,
        },
        {
          id: "pm-5",
          cardNumber: "5432 **** **** 5432",
          cardHolder: "CARLOS RODRIGUEZ",
          expiryDate: "11/25",
          type: "mastercard",
        },
      ],
      rating: 4.9,
      reviews: [
        {
          id: "rev-5",
          reviewerId: "user-1",
          reviewerName: "Juan Pérez",
          rating: 5,
          comment: "Excelente conductor, muy responsable.",
          date: "2023-08-12",
        },
        {
          id: "rev-6",
          reviewerId: "user-2",
          reviewerName: "María González",
          rating: 5,
          comment: "El mejor conductor, siempre puntual y amable.",
          date: "2023-10-25",
        },
      ],
      notifications: [
        {
          id: "notif-5",
          userId: "user-3",
          title: "Viaje finalizado",
          message: "Tu viaje desde Universidad ha finalizado. ¡Gracias por usar UniRide!",
          type: "success",
          read: false,
          date: new Date(Date.now() - 172800000).toISOString(),
          relatedRideId: "ride-8",
        },
      ],
      createdAt: "2023-03-10",
      createdBy: "admin-1",
    },
    // Personal administrativo que solo es pasajero
    {
      id: "user-4",
      firstName: "Ana",
      lastName: "Martínez",
      legajo: "11111",
      dni: "28123456",
      email: "ana.martinez@universidad.edu",
      phone: "11-1111-2222",
      institutionalRole: ["staff"],
      uniRideRole: ["passenger"],
      password: "ana123",
      paymentMethods: [
        {
          id: "pm-6",
          cardNumber: "4000 **** **** 4000",
          cardHolder: "ANA MARTINEZ",
          expiryDate: "06/26",
          type: "visa",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2023-04-05",
      createdBy: "admin-1",
    },
    // Estudiante que solo es conductor
    {
      id: "user-5",
      firstName: "Diego",
      lastName: "López",
      legajo: "22222",
      dni: "29987654",
      email: "diego.lopez@universidad.edu",
      phone: "11-2222-3333",
      institutionalRole: ["student"],
      uniRideRole: ["driver"],
      password: "diego123",
      paymentMethods: [
        {
          id: "pm-7",
          cardNumber: "5100 **** **** 5100",
          cardHolder: "DIEGO LOPEZ",
          expiryDate: "09/25",
          type: "mastercard",
          isDefault: true,
        },
      ],
      rating: 4.2,
      reviews: [
        {
          id: "rev-7",
          reviewerId: "user-4",
          reviewerName: "Ana Martínez",
          rating: 4,
          comment: "Buen conductor, música agradable.",
          date: "2023-11-15",
        },
      ],
      notifications: [],
      createdAt: "2023-05-12",
      createdBy: "admin-1",
    },
    // Profesor que tiene múltiples roles institucionales y es conductor
    {
      id: "user-6",
      firstName: "Laura",
      lastName: "Fernández",
      legajo: "33333",
      dni: "27456789",
      email: "laura.fernandez@universidad.edu",
      phone: "11-3333-4444",
      institutionalRole: ["professor", "staff"], // Múltiples roles institucionales
      uniRideRole: ["driver", "passenger"],
      password: "laura123",
      paymentMethods: [
        {
          id: "pm-8",
          cardNumber: "3400 **** **** 3400",
          cardHolder: "LAURA FERNANDEZ",
          expiryDate: "12/26",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.7,
      reviews: [],
      notifications: [],
      createdAt: "2023-06-20",
      createdBy: "admin-1",
    },
    // Estudiante que solo es pasajero
    {
      id: "user-7",
      firstName: "Roberto",
      lastName: "Silva",
      legajo: "44444",
      dni: "26789123",
      email: "roberto.silva@universidad.edu",
      phone: "11-4444-5555",
      institutionalRole: ["student"],
      uniRideRole: ["passenger"],
      password: "roberto123",
      paymentMethods: [
        {
          id: "pm-9",
          cardNumber: "4300 **** **** 4300",
          cardHolder: "ROBERTO SILVA",
          expiryDate: "04/27",
          type: "visa",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2023-07-08",
      createdBy: "admin-1",
    },
    // Más estudiantes con diferentes combinaciones
    {
      id: "user-8",
      firstName: "Sofía",
      lastName: "Morales",
      legajo: "55555",
      dni: "25678912",
      email: "sofia.morales@universidad.edu",
      phone: "11-5555-6666",
      institutionalRole: ["student"],
      uniRideRole: ["driver", "passenger"],
      password: "sofia123",
      paymentMethods: [
        {
          id: "pm-10",
          cardNumber: "4400 **** **** 4400",
          cardHolder: "SOFIA MORALES",
          expiryDate: "07/27",
          type: "visa",
          isDefault: true,
        },
      ],
      rating: 4.6,
      reviews: [],
      notifications: [],
      createdAt: "2023-08-15",
      createdBy: "admin-1",
    },
    {
      id: "user-9",
      firstName: "Martín",
      lastName: "Castro",
      legajo: "66666",
      dni: "24567891",
      email: "martin.castro@universidad.edu",
      phone: "11-6666-7777",
      institutionalRole: ["student"],
      uniRideRole: ["passenger"],
      password: "martin123",
      paymentMethods: [
        {
          id: "pm-11",
          cardNumber: "5200 **** **** 5200",
          cardHolder: "MARTIN CASTRO",
          expiryDate: "08/27",
          type: "mastercard",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2023-09-10",
      createdBy: "admin-1",
    },
    // Personal con múltiples roles
    {
      id: "user-10",
      firstName: "Elena",
      lastName: "Vásquez",
      legajo: "77777",
      dni: "23456789",
      email: "elena.vasquez@universidad.edu",
      phone: "11-7777-8888",
      institutionalRole: ["staff", "professor"],
      uniRideRole: ["driver"],
      password: "elena123",
      paymentMethods: [
        {
          id: "pm-12",
          cardNumber: "3500 **** **** 3500",
          cardHolder: "ELENA VASQUEZ",
          expiryDate: "09/27",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.3,
      reviews: [],
      notifications: [],
      createdAt: "2023-10-05",
      createdBy: "admin-1",
    },
    // Más profesores
    {
      id: "user-11",
      firstName: "Ricardo",
      lastName: "Mendoza",
      legajo: "88888",
      dni: "22345678",
      email: "ricardo.mendoza@universidad.edu",
      phone: "11-8888-9999",
      institutionalRole: ["professor"],
      uniRideRole: ["passenger"],
      password: "ricardo123",
      paymentMethods: [
        {
          id: "pm-13",
          cardNumber: "4500 **** **** 4500",
          cardHolder: "RICARDO MENDOZA",
          expiryDate: "10/27",
          type: "visa",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2023-11-12",
      createdBy: "admin-1",
    },
    {
      id: "user-12",
      firstName: "Valentina",
      lastName: "Torres",
      legajo: "99999",
      dni: "21234567",
      email: "valentina.torres@universidad.edu",
      phone: "11-9999-0000",
      institutionalRole: ["professor"],
      uniRideRole: ["driver", "passenger"],
      password: "valentina123",
      paymentMethods: [
        {
          id: "pm-14",
          cardNumber: "5300 **** **** 5300",
          cardHolder: "VALENTINA TORRES",
          expiryDate: "11/27",
          type: "mastercard",
          isDefault: true,
        },
      ],
      rating: 4.9,
      reviews: [],
      notifications: [],
      createdAt: "2023-12-01",
      createdBy: "admin-1",
    },
    // Más personal administrativo
    {
      id: "user-13",
      firstName: "Gabriel",
      lastName: "Herrera",
      legajo: "10101",
      dni: "20123456",
      email: "gabriel.herrera@universidad.edu",
      phone: "11-0101-0101",
      institutionalRole: ["staff"],
      uniRideRole: ["driver", "passenger"],
      password: "gabriel123",
      paymentMethods: [
        {
          id: "pm-15",
          cardNumber: "3600 **** **** 3600",
          cardHolder: "GABRIEL HERRERA",
          expiryDate: "12/27",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.4,
      reviews: [],
      notifications: [],
      createdAt: "2024-01-15",
      createdBy: "admin-1",
    },
    // Estudiantes adicionales
    {
      id: "user-14",
      firstName: "Camila",
      lastName: "Ruiz",
      legajo: "20202",
      dni: "19012345",
      email: "camila.ruiz@universidad.edu",
      phone: "11-0202-0202",
      institutionalRole: ["student"],
      uniRideRole: ["driver"],
      password: "camila123",
      paymentMethods: [
        {
          id: "pm-16",
          cardNumber: "4600 **** **** 4600",
          cardHolder: "CAMILA RUIZ",
          expiryDate: "01/28",
          type: "visa",
          isDefault: true,
        },
      ],
      rating: 4.1,
      reviews: [],
      notifications: [],
      createdAt: "2024-02-10",
      createdBy: "admin-1",
    },
    {
      id: "user-15",
      firstName: "Andrés",
      lastName: "Jiménez",
      legajo: "30303",
      dni: "18901234",
      email: "andres.jimenez@universidad.edu",
      phone: "11-0303-0303",
      institutionalRole: ["student"],
      uniRideRole: ["passenger"],
      password: "andres123",
      paymentMethods: [
        {
          id: "pm-17",
          cardNumber: "5400 **** **** 5400",
          cardHolder: "ANDRES JIMENEZ",
          expiryDate: "02/28",
          type: "mastercard",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2024-03-05",
      createdBy: "admin-1",
    },
    // Usuarios adicionales para tener una base de datos más robusta
    {
      id: "user-16",
      firstName: "Lucía",
      lastName: "Ramírez",
      legajo: "40404",
      dni: "17890123",
      email: "lucia.ramirez@universidad.edu",
      phone: "11-0404-0404",
      institutionalRole: ["student"],
      uniRideRole: ["driver", "passenger"],
      password: "lucia123",
      paymentMethods: [
        {
          id: "pm-18",
          cardNumber: "3700 **** **** 3700",
          cardHolder: "LUCIA RAMIREZ",
          expiryDate: "03/28",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.8,
      reviews: [],
      notifications: [],
      createdAt: "2024-04-01",
      createdBy: "admin-1",
    },
    {
      id: "user-17",
      firstName: "Fernando",
      lastName: "Delgado",
      legajo: "50505",
      dni: "16789012",
      email: "fernando.delgado@universidad.edu",
      phone: "11-0505-0505",
      institutionalRole: ["professor"],
      uniRideRole: ["driver"],
      password: "fernando123",
      paymentMethods: [
        {
          id: "pm-19",
          cardNumber: "4700 **** **** 4700",
          cardHolder: "FERNANDO DELGADO",
          expiryDate: "04/28",
          type: "visa",
          isDefault: true,
        },
      ],
      rating: 4.6,
      reviews: [],
      notifications: [],
      createdAt: "2024-04-15",
      createdBy: "admin-1",
    },
    {
      id: "user-18",
      firstName: "Natalia",
      lastName: "Guerrero",
      legajo: "60606",
      dni: "15678901",
      email: "natalia.guerrero@universidad.edu",
      phone: "11-0606-0606",
      institutionalRole: ["staff"],
      uniRideRole: ["passenger"],
      password: "natalia123",
      paymentMethods: [
        {
          id: "pm-20",
          cardNumber: "5500 **** **** 5500",
          cardHolder: "NATALIA GUERRERO",
          expiryDate: "05/28",
          type: "mastercard",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2024-05-01",
      createdBy: "admin-1",
    },
    {
      id: "user-19",
      firstName: "Sebastián",
      lastName: "Medina",
      legajo: "70707",
      dni: "14567890",
      email: "sebastian.medina@universidad.edu",
      phone: "11-0707-0707",
      institutionalRole: ["student"],
      uniRideRole: ["driver", "passenger"],
      password: "sebastian123",
      paymentMethods: [
        {
          id: "pm-21",
          cardNumber: "3800 **** **** 3800",
          cardHolder: "SEBASTIAN MEDINA",
          expiryDate: "06/28",
          type: "amex",
          isDefault: true,
        },
      ],
      rating: 4.5,
      reviews: [],
      notifications: [],
      createdAt: "2024-05-20",
      createdBy: "admin-1",
    },
    {
      id: "user-20",
      firstName: "Daniela",
      lastName: "Paredes",
      legajo: "80808",
      dni: "13456789",
      email: "daniela.paredes@universidad.edu",
      phone: "11-0808-0808",
      institutionalRole: ["professor"],
      uniRideRole: ["passenger"],
      password: "daniela123",
      paymentMethods: [
        {
          id: "pm-22",
          cardNumber: "4800 **** **** 4800",
          cardHolder: "DANIELA PAREDES",
          expiryDate: "07/28",
          type: "visa",
          isDefault: true,
        },
      ],
      notifications: [],
      createdAt: "2024-06-10",
      createdBy: "admin-1",
    },
  ],
  rides: [
    // Viajes de Juan (user-1)
    {
      id: "ride-1",
      driverId: "user-1",
      driverName: "Juan Pérez",
      origin: "Palermo",
      destination: "Universidad",
      date: new Date().toISOString().split("T")[0], // Hoy
      departureTime: "08:00",
      estimatedArrivalTime: "08:30",
      availableSeats: 3,
      maxDetourMeters: 500,
      maxWaitingMinutes: 5,
      passengers: [
        {
          id: "user-2",
          name: "María González",
          status: "confirmed",
          paymentMethodId: "pm-3",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. Santa Fe",
      status: "active",
      originCoords: locationCoords["Palermo"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Palermo - Punto de partida",
          coords: locationCoords["Palermo"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:00",
        },
        {
          name: "Av. Santa Fe y Scalabrini Ortiz",
          coords: { lat: -34.588446, lng: -58.402071 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:10",
        },
        {
          name: "Av. Santa Fe y Pueyrredón",
          coords: { lat: -34.588446, lng: -58.392071 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:20",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:30",
        },
      ],
    },
    {
      id: "ride-4",
      driverId: "user-1",
      driverName: "Juan Pérez",
      origin: "Universidad",
      destination: "Palermo",
      date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Mañana
      departureTime: "17:30",
      estimatedArrivalTime: "18:00",
      availableSeats: 3,
      maxDetourMeters: 800,
      maxWaitingMinutes: 10,
      passengers: [],
      direction: "fromUniversity",
      notes: "Salgo desde el estacionamiento principal",
      status: "active",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Palermo"],
      route: [
        {
          name: "Universidad - Estacionamiento principal",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "17:30",
        },
        {
          name: "Av. Córdoba y Pueyrredón",
          coords: { lat: -34.599446, lng: -58.392071 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "17:40",
        },
        {
          name: "Av. Córdoba y Scalabrini Ortiz",
          coords: { lat: -34.599446, lng: -58.402071 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "17:50",
        },
        {
          name: "Palermo - Destino final",
          coords: locationCoords["Palermo"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "18:00",
        },
      ],
    },
    {
      id: "ride-7",
      driverId: "user-1",
      driverName: "Juan Pérez",
      origin: "Palermo",
      destination: "Universidad",
      date: new Date(Date.now() - 86400000).toISOString().split("T")[0], // Ayer
      departureTime: "08:00",
      estimatedArrivalTime: "08:30",
      availableSeats: 3,
      maxDetourMeters: 500,
      maxWaitingMinutes: 5,
      passengers: [
        {
          id: "user-3",
          name: "Carlos Rodríguez",
          status: "completed",
          paymentMethodId: "pm-4",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. Santa Fe",
      status: "completed",
      originCoords: locationCoords["Palermo"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Palermo - Punto de partida",
          coords: locationCoords["Palermo"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:00",
        },
        {
          name: "Av. Santa Fe y Scalabrini Ortiz",
          coords: { lat: -34.588446, lng: -58.402071 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:10",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 3,
          isPickupPoint: false,
          estimatedTime: "08:30",
        },
      ],
    },

    // Viajes de Carlos (user-3)
    {
      id: "ride-2",
      driverId: "user-3",
      driverName: "Carlos Rodríguez",
      origin: "Universidad",
      destination: "Belgrano",
      date: new Date().toISOString().split("T")[0], // Hoy
      departureTime: "18:00",
      estimatedArrivalTime: "18:35",
      availableSeats: 4,
      maxDetourMeters: 1000,
      maxWaitingMinutes: 7,
      passengers: [],
      direction: "fromUniversity",
      notes: "Puedo hacer pequeños desvíos",
      status: "active",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Belgrano"],
      route: [
        {
          name: "Universidad - Salida principal",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "18:00",
        },
        {
          name: "Av. Las Heras y Pueyrredón",
          coords: { lat: -34.588722, lng: -58.392592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "18:10",
        },
        {
          name: "Av. Cabildo y Juramento",
          coords: { lat: -34.563589, lng: -58.442728 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "18:25",
        },
        {
          name: "Belgrano - Destino final",
          coords: locationCoords["Belgrano"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "18:35",
        },
      ],
    },
    {
      id: "ride-6",
      driverId: "user-3",
      driverName: "Carlos Rodríguez",
      origin: "Belgrano",
      destination: "Universidad",
      date: new Date(Date.now() + 172800000).toISOString().split("T")[0], // Pasado mañana
      departureTime: "08:30",
      estimatedArrivalTime: "09:05",
      availableSeats: 4,
      maxDetourMeters: 1000,
      maxWaitingMinutes: 7,
      passengers: [
        {
          id: "user-1",
          name: "Juan Pérez",
          status: "confirmed",
          paymentMethodId: "pm-1",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Cabildo y Juramento",
      status: "active",
      originCoords: locationCoords["Belgrano"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Belgrano - Punto de partida",
          coords: locationCoords["Belgrano"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:30",
        },
        {
          name: "Av. Cabildo y Monroe",
          coords: { lat: -34.553589, lng: -58.442728 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:40",
        },
        {
          name: "Av. Las Heras y Coronel Díaz",
          coords: { lat: -34.588722, lng: -58.402592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:55",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "09:05",
        },
      ],
    },
    {
      id: "ride-8",
      driverId: "user-3",
      driverName: "Carlos Rodríguez",
      origin: "Universidad",
      destination: "Belgrano",
      date: new Date(Date.now() - 172800000).toISOString().split("T")[0], // Hace dos días
      departureTime: "18:00",
      estimatedArrivalTime: "18:35",
      availableSeats: 4,
      maxDetourMeters: 1000,
      maxWaitingMinutes: 7,
      passengers: [
        {
          id: "user-2",
          name: "María González",
          status: "cancelled",
          paymentMethodId: "pm-3",
        },
      ],
      direction: "fromUniversity",
      notes: "Puedo hacer pequeños desvíos",
      status: "completed",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Belgrano"],
      route: [
        {
          name: "Universidad - Salida principal",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "18:00",
        },
        {
          name: "Av. Las Heras y Pueyrredón",
          coords: { lat: -34.588722, lng: -58.392592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "18:10",
        },
        {
          name: "Belgrano - Destino final",
          coords: locationCoords["Belgrano"],
          order: 3,
          isPickupPoint: false,
          estimatedTime: "18:35",
        },
      ],
    },

    // Viajes de María (user-2)
    {
      id: "ride-3",
      driverId: "user-2",
      driverName: "María González",
      origin: "Caballito",
      destination: "Universidad",
      date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Mañana
      departureTime: "09:30",
      estimatedArrivalTime: "10:05",
      availableSeats: 2,
      maxDetourMeters: 600,
      maxWaitingMinutes: 5,
      passengers: [],
      direction: "toUniversity",
      status: "active",
      originCoords: locationCoords["Caballito"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Caballito - Punto de partida",
          coords: locationCoords["Caballito"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "09:30",
        },
        {
          name: "Av. Rivadavia y Acoyte",
          coords: { lat: -34.619519, lng: -58.433642 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "09:40",
        },
        {
          name: "Av. Corrientes y Pueyrredón",
          coords: { lat: -34.603722, lng: -58.392592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "09:55",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "10:05",
        },
      ],
    },
    {
      id: "ride-5",
      driverId: "user-2",
      driverName: "María González",
      origin: "Universidad",
      destination: "Caballito",
      date: new Date(Date.now() + 172800000).toISOString().split("T")[0], // Pasado mañana
      departureTime: "16:00",
      estimatedArrivalTime: "16:35",
      availableSeats: 2,
      maxDetourMeters: 600,
      maxWaitingMinutes: 5,
      passengers: [
        {
          id: "user-3",
          name: "Carlos Rodríguez",
          status: "confirmed",
          paymentMethodId: "pm-4",
        },
      ],
      direction: "fromUniversity",
      status: "active",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Caballito"],
      route: [
        {
          name: "Universidad - Salida",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "16:00",
        },
        {
          name: "Av. Corrientes y Callao",
          coords: { lat: -34.603722, lng: -58.382592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "16:15",
        },
        {
          name: "Av. Rivadavia y Medrano",
          coords: { lat: -34.619519, lng: -58.423642 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "16:25",
        },
        {
          name: "Caballito - Destino final",
          coords: locationCoords["Caballito"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "16:35",
        },
      ],
    },
    {
      id: "ride-9",
      driverId: "user-2",
      driverName: "María González",
      origin: "Caballito",
      destination: "Universidad",
      date: new Date(Date.now() - 86400000).toISOString().split("T")[0], // Ayer
      departureTime: "09:30",
      estimatedArrivalTime: "10:05",
      availableSeats: 2,
      maxDetourMeters: 600,
      maxWaitingMinutes: 5,
      passengers: [
        {
          id: "user-1",
          name: "Juan Pérez",
          status: "cancelled",
          paymentMethodId: "pm-1",
        },
      ],
      direction: "toUniversity",
      status: "cancelled",
      originCoords: locationCoords["Caballito"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Caballito - Punto de partida",
          coords: locationCoords["Caballito"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "09:30",
        },
        {
          name: "Av. Rivadavia y Acoyte",
          coords: { lat: -34.619519, lng: -58.433642 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "09:40",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 3,
          isPickupPoint: false,
          estimatedTime: "10:05",
        },
      ],
    },

    // Viajes adicionales de otros usuarios
    {
      id: "ride-10",
      driverId: "user-5",
      driverName: "Diego López",
      origin: "Flores",
      destination: "Universidad",
      date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Mañana
      departureTime: "07:45",
      estimatedArrivalTime: "08:20",
      availableSeats: 3,
      maxDetourMeters: 800,
      maxWaitingMinutes: 10,
      passengers: [],
      direction: "toUniversity",
      notes: "Música variada, ambiente relajado",
      status: "active",
      originCoords: locationCoords["Flores"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Flores - Punto de partida",
          coords: locationCoords["Flores"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "07:45",
        },
        {
          name: "Av. Rivadavia y Nazca",
          coords: { lat: -34.628775, lng: -58.453593 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "07:55",
        },
        {
          name: "Av. Rivadavia y Medrano",
          coords: { lat: -34.628775, lng: -58.423593 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:05",
        },
        {
          name: "Av. Corrientes y Callao",
          coords: { lat: -34.603722, lng: -58.382592 },
          order: 4,
          isPickupPoint: true,
          estimatedTime: "08:15",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 5,
          isPickupPoint: false,
          estimatedTime: "08:20",
        },
      ],
    },
    {
      id: "ride-11",
      driverId: "user-6",
      driverName: "Laura Fernández",
      origin: "San Telmo",
      destination: "Universidad",
      date: new Date(Date.now() + 172800000).toISOString().split("T")[0], // Pasado mañana
      departureTime: "08:15",
      estimatedArrivalTime: "08:50",
      availableSeats: 2,
      maxDetourMeters: 500,
      maxWaitingMinutes: 5,
      passengers: [],
      direction: "toUniversity",
      notes: "Viaje tranquilo, no fumo",
      status: "active",
      originCoords: locationCoords["San Telmo"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "San Telmo - Punto de partida",
          coords: locationCoords["San Telmo"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:15",
        },
        {
          name: "Av. 9 de Julio y Estados Unidos",
          coords: { lat: -34.621076, lng: -58.383678 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:25",
        },
        {
          name: "Av. Corrientes y 9 de Julio",
          coords: { lat: -34.603722, lng: -58.383678 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:40",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:50",
        },
      ],
    },
    {
      id: "ride-12",
      driverId: "user-8",
      driverName: "Sofía Morales",
      origin: "Microcentro",
      destination: "Universidad",
      date: new Date().toISOString().split("T")[0], // Hoy
      departureTime: "09:00",
      estimatedArrivalTime: "09:25",
      availableSeats: 3,
      maxDetourMeters: 700,
      maxWaitingMinutes: 8,
      passengers: [
        {
          id: "user-9",
          name: "Martín Castro",
          status: "confirmed",
          paymentMethodId: "pm-11",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. Corrientes",
      status: "active",
      originCoords: locationCoords["Microcentro"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Microcentro - Punto de partida",
          coords: locationCoords["Microcentro"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "09:00",
        },
        {
          name: "Av. Corrientes y Florida",
          coords: { lat: -34.608418, lng: -58.373678 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "09:10",
        },
        {
          name: "Av. Corrientes y Callao",
          coords: { lat: -34.603722, lng: -58.382592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "09:20",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "09:25",
        },
      ],
    },
    {
      id: "ride-13",
      driverId: "user-10",
      driverName: "Elena Vásquez",
      origin: "Puerto Madero",
      destination: "Universidad",
      date: new Date(Date.now() + 259200000).toISOString().split("T")[0], // En 3 días
      departureTime: "08:45",
      estimatedArrivalTime: "09:15",
      availableSeats: 2,
      maxDetourMeters: 400,
      maxWaitingMinutes: 5,
      passengers: [],
      direction: "toUniversity",
      notes: "Viaje silencioso, perfecto para estudiar",
      status: "active",
      originCoords: locationCoords["Puerto Madero"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Puerto Madero - Punto de partida",
          coords: locationCoords["Puerto Madero"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:45",
        },
        {
          name: "Av. Alicia Moreau de Justo y Córdoba",
          coords: { lat: -34.610418, lng: -58.353678 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:55",
        },
        {
          name: "Av. Córdoba y 9 de Julio",
          coords: { lat: -34.599722, lng: -58.383678 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "09:05",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "09:15",
        },
      ],
    },
    {
      id: "ride-14",
      driverId: "user-12",
      driverName: "Valentina Torres",
      origin: "Retiro",
      destination: "Universidad",
      date: new Date().toISOString().split("T")[0], // Hoy
      departureTime: "07:30",
      estimatedArrivalTime: "08:00",
      availableSeats: 3,
      maxDetourMeters: 600,
      maxWaitingMinutes: 8,
      passengers: [
        {
          id: "user-4",
          name: "Ana Martínez",
          status: "confirmed",
          paymentMethodId: "pm-6",
        },
        {
          id: "user-7",
          name: "Roberto Silva",
          status: "confirmed",
          paymentMethodId: "pm-9",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. del Libertador",
      status: "active",
      originCoords: locationCoords["Retiro"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Retiro - Estación",
          coords: locationCoords["Retiro"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "07:30",
        },
        {
          name: "Av. del Libertador y Callao",
          coords: { lat: -34.590418, lng: -58.383678 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "07:40",
        },
        {
          name: "Av. Las Heras y Pueyrredón",
          coords: { lat: -34.588722, lng: -58.392592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "07:50",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:00",
        },
      ],
    },
    {
      id: "ride-15",
      driverId: "user-14",
      driverName: "Camila Ruiz",
      origin: "Villa Crespo",
      destination: "Universidad",
      date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Mañana
      departureTime: "08:20",
      estimatedArrivalTime: "08:50",
      availableSeats: 2,
      maxDetourMeters: 500,
      maxWaitingMinutes: 5,
      passengers: [],
      direction: "toUniversity",
      status: "active",
      originCoords: locationCoords["Villa Crespo"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Villa Crespo - Punto de partida",
          coords: locationCoords["Villa Crespo"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:20",
        },
        {
          name: "Av. Corrientes y Scalabrini Ortiz",
          coords: { lat: -34.599819, lng: -58.406348 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:30",
        },
        {
          name: "Av. Corrientes y Pueyrredón",
          coords: { lat: -34.603722, lng: -58.392592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:40",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:50",
        },
      ],
    },
    {
      id: "ride-16",
      driverId: "user-16",
      driverName: "Lucía Ramírez",
      origin: "Universidad",
      destination: "Núñez",
      date: new Date().toISOString().split("T")[0], // Hoy
      departureTime: "19:00",
      estimatedArrivalTime: "19:30",
      availableSeats: 3,
      maxDetourMeters: 800,
      maxWaitingMinutes: 10,
      passengers: [],
      direction: "fromUniversity",
      notes: "Salgo después de clases",
      status: "active",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Núñez"],
      route: [
        {
          name: "Universidad - Salida",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "19:00",
        },
        {
          name: "Av. Las Heras y Coronel Díaz",
          coords: { lat: -34.588722, lng: -58.402592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "19:10",
        },
        {
          name: "Av. del Libertador y Cabildo",
          coords: { lat: -34.555021, lng: -58.451246 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "19:20",
        },
        {
          name: "Núñez - Destino final",
          coords: locationCoords["Núñez"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "19:30",
        },
      ],
    },
    {
      id: "ride-17",
      driverId: "user-17",
      driverName: "Fernando Delgado",
      origin: "Almagro",
      destination: "Universidad",
      date: new Date(Date.now() + 172800000).toISOString().split("T")[0], // Pasado mañana
      departureTime: "07:45",
      estimatedArrivalTime: "08:20",
      availableSeats: 4,
      maxDetourMeters: 1000,
      maxWaitingMinutes: 10,
      passengers: [
        {
          id: "user-9",
          name: "Martín Castro",
          status: "confirmed",
          paymentMethodId: "pm-11",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. Corrientes",
      status: "active",
      originCoords: locationCoords["Almagro"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Almagro - Punto de partida",
          coords: locationCoords["Almagro"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "07:45",
        },
        {
          name: "Av. Corrientes y Medrano",
          coords: { lat: -34.610485, lng: -58.430257 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "07:55",
        },
        {
          name: "Av. Corrientes y Pueyrredón",
          coords: { lat: -34.603722, lng: -58.392592 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:10",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:20",
        },
      ],
    },
    {
      id: "ride-18",
      driverId: "user-19",
      driverName: "Sebastián Medina",
      origin: "Universidad",
      destination: "Colegiales",
      date: new Date(Date.now() + 86400000).toISOString().split("T")[0], // Mañana
      departureTime: "17:45",
      estimatedArrivalTime: "18:20",
      availableSeats: 2,
      maxDetourMeters: 600,
      maxWaitingMinutes: 7,
      passengers: [],
      direction: "fromUniversity",
      status: "active",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Colegiales"],
      route: [
        {
          name: "Universidad - Salida",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "17:45",
        },
        {
          name: "Av. Las Heras y Pueyrredón",
          coords: { lat: -34.588722, lng: -58.392592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "17:55",
        },
        {
          name: "Av. Cabildo y Dorrego",
          coords: { lat: -34.577473, lng: -58.437766 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "18:10",
        },
        {
          name: "Colegiales - Destino final",
          coords: locationCoords["Colegiales"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "18:20",
        },
      ],
    },
    // Viajes completados para mostrar historial
    {
      id: "ride-19",
      driverId: "user-1",
      driverName: "Juan Pérez",
      origin: "Palermo",
      destination: "Universidad",
      date: new Date(Date.now() - 259200000).toISOString().split("T")[0], // Hace 3 días
      departureTime: "08:00",
      estimatedArrivalTime: "08:30",
      availableSeats: 3,
      maxDetourMeters: 500,
      maxWaitingMinutes: 5,
      passengers: [
        {
          id: "user-2",
          name: "María González",
          status: "completed",
          paymentMethodId: "pm-3",
        },
        {
          id: "user-4",
          name: "Ana Martínez",
          status: "completed",
          paymentMethodId: "pm-6",
        },
      ],
      direction: "toUniversity",
      notes: "Paso por Av. Santa Fe",
      status: "completed",
      originCoords: locationCoords["Palermo"],
      destinationCoords: locationCoords["Universidad"],
      route: [
        {
          name: "Palermo - Punto de partida",
          coords: locationCoords["Palermo"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "08:00",
        },
        {
          name: "Av. Santa Fe y Scalabrini Ortiz",
          coords: { lat: -34.588446, lng: -58.402071 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "08:10",
        },
        {
          name: "Av. Santa Fe y Pueyrredón",
          coords: { lat: -34.588446, lng: -58.392071 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "08:20",
        },
        {
          name: "Universidad - Destino final",
          coords: locationCoords["Universidad"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "08:30",
        },
      ],
    },
    {
      id: "ride-20",
      driverId: "user-3",
      driverName: "Carlos Rodríguez",
      origin: "Universidad",
      destination: "Belgrano",
      date: new Date(Date.now() - 345600000).toISOString().split("T")[0], // Hace 4 días
      departureTime: "18:00",
      estimatedArrivalTime: "18:35",
      availableSeats: 4,
      maxDetourMeters: 1000,
      maxWaitingMinutes: 7,
      passengers: [
        {
          id: "user-7",
          name: "Roberto Silva",
          status: "completed",
          paymentMethodId: "pm-9",
        },
        {
          id: "user-11",
          name: "Ricardo Mendoza",
          status: "completed",
          paymentMethodId: "pm-13",
        },
      ],
      direction: "fromUniversity",
      notes: "Puedo hacer pequeños desvíos",
      status: "completed",
      originCoords: locationCoords["Universidad"],
      destinationCoords: locationCoords["Belgrano"],
      route: [
        {
          name: "Universidad - Salida principal",
          coords: locationCoords["Universidad"],
          order: 1,
          isPickupPoint: false,
          estimatedTime: "18:00",
        },
        {
          name: "Av. Las Heras y Pueyrredón",
          coords: { lat: -34.588722, lng: -58.392592 },
          order: 2,
          isPickupPoint: true,
          estimatedTime: "18:10",
        },
        {
          name: "Av. Cabildo y Juramento",
          coords: { lat: -34.563589, lng: -58.442728 },
          order: 3,
          isPickupPoint: true,
          estimatedTime: "18:25",
        },
        {
          name: "Belgrano - Destino final",
          coords: locationCoords["Belgrano"],
          order: 4,
          isPickupPoint: false,
          estimatedTime: "18:35",
        },
      ],
    },
  ],
  notifications: [
    // Las notificaciones ya están incluidas en los usuarios
  ],
}
